# Generated by Django 2.1.2 on 2021-11-12 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('fundacion', models.PositiveSmallIntegerField()),
                ('estadio', models.CharField(max_length=30)),
                ('aforo', models.PositiveIntegerField(default=0)),
                ('direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('fecha', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goles_local', models.PositiveSmallIntegerField()),
                ('goles_visitante', models.PositiveSmallIntegerField()),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Jornada')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornada_local', to='principal.Equipo')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jornada_visitante', to='principal.Equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anyo', models.PositiveSmallIntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='jornada',
            name='temporada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Temporada'),
        ),
        migrations.AlterUniqueTogether(
            name='jornada',
            unique_together={('temporada', 'numero')},
        ),
    ]
